apiVersion: v1
kind: Service
metadata:
  name: deploy-aks
  namespace: namespace-workflow-1729556805250
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: deploy-aks
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080