name: build-deploy-acs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set Gradlew permissions
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" | docker login gearingregistry.azurecr.io -u "${{ secrets.AZURE_CLIENT_ID }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t gearingregistry.azurecr.io/gearingrest:${{ github.sha }} .

      - name: Push Docker Image to ACR
        run: |
          docker push gearingregistry.azurecr.io/gearingrest:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to AKS
        uses: azure/setup-aks@v1
        with:
          azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
          azure-resource-group: gearing-guru
          azure-aks-name: gearing-cluster

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/gearingrest myapp=gearingregistry.azurecr.io/gearingrest:${{ github.sha }}
          kubectl rollout status deployment/gearingrest

      - name: Notify success
        if: success()
        run: echo "Deployment completed successfully!"

      - name: Notify failure
        if: failure()
        run: echo "Deployment failed!"
